### ISSUE TITLE
Create V1 and publish to marketplace

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/gha-remove-artifacts#20]
About versioning see:
- https://help.github.com/en/actions/building-actions/about-actions#versioning-your-action
- https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

`v1.0.0` and `v1` tags have to be created.

**Comment by gomorizsolt** [comment]
Thanks for the referenced guides. So it's all about creating releases and keeping the `v1` tag up-to-date unless there's a major version bump because that's an indication of bumping `v1` as well. We may automate this process in the future if possible.

**Comment by gomorizsolt** [comment]
FYI, I've cleaned up the releases and tags.

**Comment by gomorizsolt** [comment]
🔥 💥 
- https://github.com/marketplace/actions/remove-artifacts
- https://github.com/c-hive/gha-remove-artifacts/releases/tag/v1.0.0
- https://github.com/c-hive/gha-remove-artifacts/releases/tag/v1
