### ISSUE TITLE
Add API throttling

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/gha-remove-artifacts#3]
Although there're separate keys per repo and 5k available requests at a time, so hopefully a daily build will work just fine. Still, would be nice to at least get proper errors.

https://github.com/octokit/plugin-throttling.js/

https://github.com/actions/toolkit/issues/106 and https://github.com/actions/toolkit/blob/fc9958ec6a57d1b08e9a387c49971faecd0f0405/packages/github/src/github.ts#L18 might be useful on how to use plugins.

**Comment by thisismydesign** [comment]
Timebox 2h

**Comment by gomorizsolt** [comment]
Resolved by #18.
