### ISSUE TITLE
This actions causes the repo token hit abuse limits

### ISSUE THREAD

**Issue by webknjaz** [c-hive/gha-remove-artifacts#34]
This affects any other (often implicit!) use of the `GITHUB_TOKEN` within the same repo workflows: https://github.com/actions/virtual-environments/issues/1740#issuecomment-706303848.

Looking at the log https://github.com/ansible/pylibssh/runs/1232157025?check_suite_focus=true and many similar ones before, it seems like the action keeps re-fetching all the Check Runs that's been cleaned up before.

I think the fix could be having some setting like "don't go deeper than X workflows back, or Y days back".

**Comment by thisismydesign** [comment]
Hey, the age option will limit how far back the action looks. It might happen that it fetches a few more because of pagination but it shouldn't go much further back. Is there info about the token rate limits?

**Comment by webknjaz** [comment]
The rate limit should be 5k API calls per hour AFAIR.

**Comment by webknjaz** [comment]
> but it shouldn't go much further back

Sounds like a bug.. I've set it to 4 days, I think.

**Comment by webknjaz** [comment]
Turns out the retention can now be tweaked on GitHub natively: https://github.com/ansible/pylibssh/commit/384fd6f#commitcomment-43134716 / https://github.blog/changelog/2020-10-08-github-actions-ability-to-change-retention-days-for-artifacts-and-logs/

I've switched to that. Feel free to close this issue (I'm unsubscribing in case you want to keep investigating it).

**Comment by thisismydesign** [comment]
Updated the readme with this information, thanks. Someone can re-open this issue with more details if it's still a problem.
