### ISSUE TITLE
Error: HttpError

### ISSUE THREAD

**Issue by sbu-WBT** [c-hive/gha-remove-artifacts#42]
![image](https://user-images.githubusercontent.com/64100880/127753051-6e2788ef-3bc9-454b-bbf7-b157308875a2.png)

Build fails with an http error

**Comment by thisismydesign** [comment]
Please provide more info. Did you try to re-run? If the repo is public link it.

**Comment by sbu-WBT** [comment]
A rerun worked because there was only a new artifact
![image](https://user-images.githubusercontent.com/64100880/127768177-7b126cc1-8417-4369-9798-e20daf35ff6d.png)
The repo is private, sorry

**Comment by thisismydesign** [comment]
I can't tell what went wrong here, could've just been a request error on GH side, or the artifact already removed between requests, etc. But the error on our side should be more descriptive so I opened an issue for that: https://github.com/c-hive/gha-remove-artifacts/issues/43

I'm closing this as there isn't much else I can do. If this occurs more than just this once, or periodically, let me know.
