### ISSUE TITLE
Documentation: Better description of available time formats

### ISSUE THREAD

**Issue by JackAtGaia** [c-hive/gha-remove-artifacts#46]
To figure out that "14 days" would be acceptable input, I needed to go into the java script and see where the configuration is applied.

It is clear from the README.md that "1 month" is acceptable, but no discussion is present on what other formats are available.

**Comment by thisismydesign** [comment]
Thanks for the feedback, hopefully this works: https://github.com/c-hive/gha-remove-artifacts/commit/60b02b0352e5558dc40c89233c8a011cb4f5fcf1

**Comment by JackAtGaia** [comment]
Perfect.   Thanks!
