### ISSUE TITLE
Upgrade  gha-remove-artifacts to Node 16

### ISSUE THREAD

**Issue by hunterwilhelm** [c-hive/gha-remove-artifacts#55]
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by buzztaiki** [comment]
@hunterwilhelm Would you make release for #56 ?

**Comment by thisismydesign** [comment]
@buzztaiki i will when im back from vacation in december. Until then you can use the action from master
