### ISSUE TITLE
Upgrade gha-remove-artifacts to Node 20

### ISSUE THREAD

**Issue by vanialadev** [c-hive/gha-remove-artifacts#60]
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by jens-maus** [comment]
Same for me. @thisismydesign please update to Node20 to allow to continue to use this action in workflows.

**Comment by echoix** [comment]
There is no longer active development, but this action is still useful since the native solution only allows choosing the number of days of new artifacts, not other logic, like keeping the latest artifact longer regardless of that number of days.

**Comment by thisismydesign** [comment]
Hey, thanks for reporting. I'm on vacation right now but happy to merge a pr. Otherwise i can fix it april.

**Comment by coder-xiaomo** [comment]
@thisismydesign have a good vacation!

i update node version from 16 to 20 in action.yml (similar to #56) and create a pr: https://github.com/c-hive/gha-remove-artifacts/issues/60

**Comment by thisismydesign** [comment]
Thank you, release in https://github.com/c-hive/gha-remove-artifacts/releases/tag/v1.4.0 and updated the v1 tag as well.

**Comment by echoix** [comment]
Most actions switched to a different major version when changing node version

**Comment by thisismydesign** [comment]
@echoix I don't believe this is a breaking change and bumping a major version would require every user to update their workflow.
